[build]
  publish = "client/dist"
  command = "cd client && yarn build"
[build.environment]
  API_URL='/api'
[[redirects]]
  from = "/api/*"
  status = 200
  to = "https://37g2d87rp7.execute-api.eu-west-2.amazonaws.com/prod/:splat"
[[redirects]]
  from = "/*"
  status = 200
  to = "/"
