[build]
  base = "client"
  publish = "client/dist"
  command = "yarn build"
[build.environment]
  API_URL='https://37g2d87rp7.execute-api.eu-west-2.amazonaws.com/prod'
[[redirects]]
  from = "/*"
  status = 200
  to = "/"
